# Generated by Django 3.0.6 on 2020-05-30 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagramapp', '0002_auto_20200530_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='caption',
            field=models.TextField(default='2'),
        ),
    ]
