# Generated by Django 3.0.6 on 2020-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_auto_20200530_1928'),
    ]
    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('followers', models.CharField(max_length=20)),
                ('following', models.CharField(max_length=20)),
                ('posts', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='sample@gmail.com', max_length=254),
        ),
    ]
